### ISSUE TITLE
Problem while "include os specific vars"

### ISSUE THREAD

**Issue by tbludau** [linux-system-roles/sap-hana-preconfigure#1]
A variable will be defined three times. This looks like, if this is not the perfect way. I did not tested it with RHEL 7.3 an 7.2. 

TASK [sap-hana-preconfigure : include os specific vars] 
*************************************************************
 [WARNING]: While constructing a mapping from /tmp/dev/ansible/sap-hana-preconfigure/vars/RedHat_7.yml, line 5,
column 1, found a duplicate dict key (sap_hana_preconfigure_min_packages). Using last defined value only.
 [WARNING]: While constructing a mapping from /tmp/dev/ansible/sap-hana-preconfigure/vars/RedHat_7.yml, line 5,
column 1, found a duplicate dict key (when). Using last defined value only.
ok: [40.114.142.135] => (item=/tmp/dev/ansible/sap-hana-preconfigure/vars/RedHat_7.yml)

**Comment by rhmk** [comment]
Hi Thomas,
the when statement is not working in variables file :-( Let me try if jinja2 is working ..., so instead of:

```yaml
sap_hana_preconfigure_min_packages:
  - kernel-3.10.0-327.62.4.el7
  - systemd-219-19.el7_2.4
when: ansible_distribution_version == "7.2"
```
we should try
```yaml
{% if ansible_distribution_version == "7.2"  %}
sap_hana_preconfigure_min_packages:
  - kernel-3.10.0-327.62.4.el7
  - systemd-219-19.el7_2.4
{% endif %}
```
