### ISSUE TITLE
Use ansible reboot module

### ISSUE THREAD

**Issue by Klaas-** [linux-system-roles/sap-hana-preconfigure#55]
As soon as you don't support ansible 2.6 anymore you can move to reboot module
https://github.com/linux-system-roles/sap-hana-preconfigure/blob/46330da810bcce6403a5786589d31324394919aa/tasks/RedHat/installation.yml#L81-L95

would become:
```
- name: Reboot if required
  reboot:
    reboot_timeout: "{{ sap_hana_preconfigure_reboot_timeout }}"
  when: sap_hana_preconfigure_reboot_after_update == true and sap_hana_preconfigure_register_reboot_required.rc == 1
```
